"""
test_groq.py

Isolated connectivity test for the Groq LLM integration.
Sends a single hardcoded message to the Groq inference API and prints
the response, confirming that:
    1. The GROQ_API_KEY in .env is valid and loaded correctly.
    2. The groq package is installed and importable.
    3. Network connectivity to Groq's API is available.
    4. The target model (llama-3.3-70b-versatile) is accessible on the account.

Use this before running the full pipeline to rule out Groq as the source
of any LLM failures.

Usage:
    1. Ensure GROQ_API_KEY is set in .env
    2. Run:  python test_groq.py

API compatibility note:
    Groq's Python SDK mirrors the OpenAI SDK interface exactly
    (client.chat.completions.create, same message schema, same response shape).
    Any code written for openai.ChatCompletion is directly portable to Groq
    by swapping the client instantiation — no other changes needed.
"""

import os
from dotenv import load_dotenv
from groq import Groq

# Load .env into the process environment so GROQ_API_KEY is accessible
# via os.getenv without being hard-coded in source or exported as a shell variable.
load_dotenv()

# Instantiate the Groq client with the API key from the environment.
# The Groq client is synchronous and stateless — safe to create once at
# module level and reuse across multiple calls in a longer script.
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# Send a single-turn chat completion request to the Groq inference API.
#
# Model choice — llama-3.3-70b-versatile:
#   The largest freely available Llama 3.3 variant on Groq. Chosen here
#   for maximum response quality in the smoke test; the production pipeline
#   may use a smaller/faster model (e.g. llama-3.1-8b-instant) to reduce latency.
#
# messages format — OpenAI-compatible chat schema:
#   A list of {"role": ..., "content": ...} dicts representing the conversation.
#   "system" role sets behaviour/persona; "user" role is the human turn;
#   "assistant" role represents prior model replies (used for multi-turn context).
#   This test uses a single "user" turn — sufficient to verify the connection.
#
# max_tokens=100:
#   Hard cap on the response length. 100 tokens ≈ 75 words — enough for a
#   greeting while preventing runaway generation that would slow down the test.
response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",  # best free Groq model — fast + smart
    messages=[
        {
            "role": "user",
            "content": "Say hello in one sentence like a helpful AI assistant."
        }
    ],
    max_tokens=100,  # limit response length — 100 tokens ≈ 75 words
)

# Extract the reply text from the response object.
# response.choices — list of candidate completions (n=1 by default, so always one entry)
# [0]              — first (and only) completion candidate
# .message.content — the raw text string generated by the model
print(response.choices[0].message.content)